### ISSUE TITLE
Readme example not working for AWS

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-it/cloudsecrets#28]
Running the example cli command for creating a secret using AWS provider instead of GCP throws an error 
```
cloud-secrets -E -p AWS -s testing -k YETANOTHER -v SECRETVALUE                                                                    :(
Traceback (most recent call last):
  File "/home/alberto/.local/bin/cloud-secrets", line 8, in <module>
    sys.exit(main())
  File "/home/alberto/cloudsecrets/cloudsecrets/cloudsecrets/cli/__init__.py", line 109, in main
    s.set(args.key, val)
  File "/home/alberto/cloudsecrets/cloudsecrets/cloudsecrets/__init__.py", line 93, in set
    self.update()
  File "/home/alberto/cloudsecrets/cloudsecrets/cloudsecrets/aws.py", line 70, in update
    secret = self.connection.put_secret_value(
  File "/home/alberto/.local/lib/python3.8/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/alberto/.local/lib/python3.8/site-packages/botocore/client.py", line 558, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/alberto/.local/lib/python3.8/site-packages/botocore/client.py", line 606, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/alberto/.local/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter SecretString, value: b'{"YETANOTHER": "U0VDUkVUVkFMVUU="}', type: <class 'bytes'>, valid types: 
```

**Comment by The-smooth-operator** [comment]
Can't reproduce it anymore /shrug
