### ISSUE TITLE
Add support for creating a secret from a JSON file

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-it/cloudsecrets#31]
When using AWS as a provider, and supplying a file for input, cloud-secrets throws a NotImplementedError
```
cloud-secrets -p aws -E -f /tmp/secret.json -s secret                                                       :(
Traceback (most recent call last):                                                                                                        
  File "/home/alberto/.local/bin/cloud-secrets", line 8, in <module>
    sys.exit(main())
  File "/home/alberto/.local/lib/python3.8/site-packages/cloudsecrets/cli/__init__.py", line 112, in main
    raise NotImplementedError
NotImplementedError
```

**Comment by The-smooth-operator** [comment]
It's possible to create a secret from a file, however it has to be wrapped in a key.
This will work `cloud-secrets -p aws -E -k fake -f /tmp/my-secret.json -s my-secrete`
But the secret created will be inside of the key "fake".
